# Generated by Django 6.0.4 on 2026-05-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlaggedTransaction',
            fields=[
                ('transaction_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('account_from', models.CharField(max_length=50)),
                ('account_to', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('timestamp', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('is_flagged', models.BooleanField()),
                ('processed_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Flagged Transaction',
                'verbose_name_plural': 'Flagged Transactions',
                'db_table': 'core_transaction_flagged',
                'managed': False,
            },
        ),
    ]
